name: CI

on:
  push:
    branches: [ add-ci-tests ]
  pull_request:
    branches: [ add-ci-tests ]

jobs:
  apiato-tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Apiato Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Tests
        run: vendor/bin/phpunit app/
